"""Add CHAU table

Revision ID: 0f6322bd283f
Revises: acc3a4496c7a
Create Date: 2026-01-30 16:11:42.312591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6322bd283f'
down_revision: Union[str, None] = 'acc3a4496c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CHAU',
    sa.Column('chau_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_chau', sa.String(), nullable=True),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('mo_ta', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chau_id')
    )
    op.create_index(op.f('ix_CHAU_chau_id'), 'CHAU', ['chau_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CHAU_chau_id'), table_name='CHAU')
    op.drop_table('CHAU')
    # ### end Alembic commands ###
