"""add dao table

Revision ID: d80b24e8958f
Revises: 0f6322bd283f
Create Date: 2026-02-09 21:19:31.038773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80b24e8958f'
down_revision: Union[str, None] = '0f6322bd283f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DAO',
    sa.Column('dao_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_dao', sa.String(), nullable=True),
    sa.Column('chau_id', sa.Integer(), nullable=False),
    sa.Column('dia_chi', sa.String(), nullable=True),
    sa.Column('mo_ta', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chau_id'], ['CHAU.chau_id'], ),
    sa.PrimaryKeyConstraint('dao_id')
    )
    op.create_index(op.f('ix_DAO_dao_id'), 'DAO', ['dao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DAO_dao_id'), table_name='DAO')
    op.drop_table('DAO')
    # ### end Alembic commands ###
